"""initial schema with indexes

Revision ID: d5140776243f
Revises: 
Create Date: 2026-05-06 06:25:39.074046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5140776243f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('gender_probability', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.String(), nullable=False),
    sa.Column('country_id', sa.String(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('country_probability', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_profiles_age', 'profiles', ['age'], unique=False)
    op.create_index('idx_profiles_age_group', 'profiles', ['age_group'], unique=False)
    op.create_index('idx_profiles_country_age', 'profiles', ['country_id', 'age'], unique=False)
    op.create_index('idx_profiles_country_id', 'profiles', ['country_id'], unique=False)
    op.create_index('idx_profiles_created_at', 'profiles', ['created_at'], unique=False)
    op.create_index('idx_profiles_gender', 'profiles', ['gender'], unique=False)
    op.create_index('idx_profiles_gender_age_group', 'profiles', ['gender', 'age_group'], unique=False)
    op.create_index('idx_profiles_gender_country', 'profiles', ['gender', 'country_id'], unique=False)
    op.create_index('idx_profiles_gender_country_age_group', 'profiles', ['gender', 'country_id', 'age_group'], unique=False)
    op.create_table('users',
    sa.Column('github_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    op.drop_index('idx_profiles_gender_country_age_group', table_name='profiles')
    op.drop_index('idx_profiles_gender_country', table_name='profiles')
    op.drop_index('idx_profiles_gender_age_group', table_name='profiles')
    op.drop_index('idx_profiles_gender', table_name='profiles')
    op.drop_index('idx_profiles_created_at', table_name='profiles')
    op.drop_index('idx_profiles_country_id', table_name='profiles')
    op.drop_index('idx_profiles_country_age', table_name='profiles')
    op.drop_index('idx_profiles_age_group', table_name='profiles')
    op.drop_index('idx_profiles_age', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
